### Subject
Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance.
* Logistic Regression
* Decision Tree
* Support Vector Machine (SVM)
* Random Forest


In [2]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
iris = load_iris()

Logistic Regression

In [3]:
lr_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
lr_scores

array([0.96078431, 0.92156863, 0.95833333])

In [4]:
np.average(lr_scores)

0.9468954248366014

Decision Tree

In [5]:
dt_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dt_scores

array([0.98039216, 0.92156863, 0.97916667])

In [6]:
np.average(dt_scores)

0.960375816993464

Support Vector Machine (SVM)

In [7]:
sv_scores = cross_val_score(SVC(), iris.data, iris.target)
sv_scores

array([0.98039216, 0.96078431, 0.97916667])

In [8]:
np.average(sv_scores)

0.9734477124183006

Random Forest

In [9]:
rf_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rf_scores

array([0.98039216, 0.94117647, 0.97916667])

In [10]:
np.average(rf_scores)

0.9669117647058822

### Answer
SVM classifier has best score 0.9734477124183006